---
- name: Setup users
  hosts: all
  become: yes

  vars_files:
    - users-vars.yml

  tasks:
  
  - name: create user
    no_log: yes 
    with_items: "{{ lookup('dict', users) }}"
    user:
      name: "{{ item.value.name }}"
      comment: "{{ item.value.name }}@example.com"
      create_home: yes
      password: "{{ item.value.password | password_hash('sha512') }}"
      update_password: on_create
